USE ScratchDB;
GO

DROP TABLE IF EXISTS #N;

CREATE TABLE #N
(
	Num	INT NOT NULL
		PRIMARY KEY
);
GO

INSERT INTO #N
SELECT	ROW_NUMBER() OVER (ORDER BY c.object_id) AS Num
FROM	sys.columns AS c;

SELECT	COUNT(*) OVER ()
		, DATEADD(d, Num, '19760517')
		, DATENAME(dw, DATEADD(d, Num, '19760517'))
FROM	#N -- Use a numbers utility table
WHERE	DATEADD(d, Num, '19760517') < '19770101' 
		AND DATENAME(dw, DATEADD(d, Num, '19760517')) NOT IN ('Saturday', 'Sunday')
ORDER BY Num;